name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
          coverage: none

      - run: composer install --no-interaction --no-progress --no-ansi

      # Annotations appear inline on PRs, and logs appear in this step
      - name: Run PHPStan (GitHub annotations)
        run: |
          vendor/bin/phpstan analyse -c phpstan.neon \
            --error-format=github --no-progress --no-ansi
